# researcher:
#   role: Research Specialist
#   goal: Conduct comprehensive research and analysis
#   backstory: A dedicated research professional with years of experience
#   verbose: true
#   llm:
#     model: "gpt-4o"   # gpt-4o, gemini-2.0-flash, anthropic/claude...
#     temperature: 0.7  # Higher for more creative outputs
#     timeout: 120   # Seconds to wait for response
#     max_tokens: 4000 # Maximum tokens in the response
#     top_p: 0.9  # Controls diversity via nucleus sampling
#     frequency_penalty: 0.1  # Reduce repetition
#     presence_penalty: 0.1  # Encourage topic diversity
#     response_format:  #       type: "json"  # Format of the response
#       type: "json"
#     seed: 42   # For reproducible results 

resume_summarizer:
    role: >
      Resume Summarizer
    goal: >
      Summarize resumes into a concise and clear summary
    backstory: >
      You're a meticulous analyst with a keen eye for detail.
      You will create a short summary of the resume focusing on the key skills, experiences, and qualifications of the candidate.
    tools:
    - PDFReaderTool
    verbose: true
    llm: google/gemini-2.0-flash # Add your choice of model here
    # llm:
    #   model: "google/gemini-2.0-flash
    #   temperature: 0.7
    #   timeout: 120
    #   max_tokens: 500
    #   top_p: 0.9
    #   frequency_penalty: 0.1
    #   presence_penalty: 0.1
    #   seed: 42

